language: node_js
node_js:
  - "stable"
install:
  - npm install
script:
  - npm run build --report
branches:
  only:
    - master
deploy:
  provider: pages
  target_branch: gh_pages
  skip_cleanup: true
  local_dir: dist
  github_token: $GITHUB_TOKEN
  on:
    branch: master
